### PR TITLE
go changes - switched to pgx

### PR DESCRIPTION
**Pull request by abenz1267**
Hi,

here's your requested PR. Feel free to test it.

Regards

### CODE REVIEW

**Comment by travisluong** [comment]
I get an exit status 1 as soon as I hit the `/loadtest` endpoint. Other endpoints work fine though. Any idea what I might be missing?

```
❯ go run main.go
2022/02/08 21:19:03 HELLO WORLD!!!!
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /hello                    --> main.setupRouter.func1 (3 handlers)
[GIN-debug] GET    /loadtest                 --> main.setupRouter.func2 (3 handlers)
[GIN-debug] GET    /ping                     --> main.setupRouter.func3 (3 handlers)
[GIN-debug] GET    /user/:name               --> main.setupRouter.func4 (3 handlers)
[GIN-debug] POST   /admin                    --> main.setupRouter.func5 (4 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :8080
[GIN] 2022/02/08 - 21:19:12 | 404 |         569ns |             ::1 | GET      "/"
2022/02/08 21:19:16 closed pool
exit status 1
```

**Comment by abenz1267** [comment]
Maybe because of the empty password. Could you pull and try again?

**Comment by travisluong** [comment]
Thanks. That worked. These were the results.

```
Running 10s test @ http://localhost:8080/loadtest
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.47ms    1.70ms  34.71ms   97.38%
    Req/Sec     3.78k   817.41     5.00k    74.75%
  75941 requests in 10.10s, 466.91MB read
Requests/sec:   7517.37
Transfer/sec:     46.22MB
```

One last request, can you make it a separate file from the original? I'd like to keep the original for record keeping.

**Comment by abenz1267** [comment]
> Thanks. That worked. These were the results.
> 
> ```
> Running 10s test @ http://localhost:8080/loadtest
>   2 threads and 10 connections
>   Thread Stats   Avg      Stdev     Max   +/- Stdev
>     Latency     1.47ms    1.70ms  34.71ms   97.38%
>     Req/Sec     3.78k   817.41     5.00k    74.75%
>   75941 requests in 10.10s, 466.91MB read
> Requests/sec:   7517.37
> Transfer/sec:     46.22MB
> ```
> 
> One last request, can you make it a separate file from the original? I'd like to keep the original for record keeping.

Ok, done, but i've added maxcon and idlecon settings to your lib/pg version, as your result is flawed no matter what without setting it.

**Comment by travisluong** [comment]
Thanks for the PR.

I had to comment out `dbPool.close()` for it to work, btw.

**Comment by abenz1267** [comment]
Keep in mind that your lib/pg result for Go is still flawed though. I've also included maxopensconns and maxidleconns settings in this PR for lib/pq. You should re-benchmark it as well, otherwise your result is highly flawed.

**Pull request merged**
